image: barichello/godot-ci:3.4.4

variables:
  EXPORT_NAME: void_defender

stages:
  - cleanup
  - test
  - export
  - deploy

unit-test:
  stage: test
  script:
    - godot --editor --quit
    - godot -d -s addons/gut/gut_cmdln.gd


web:
  stage: export
  script:
    - godot --editor --quit
    - mkdir -v -p build/web
    - godot -v --export "HTML5" build/web/index.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/web

linux:
  stage: export
  script:
    - godot --editor --quit
    - mkdir -v -p build/linux
    - godot -v --export "Linux/X11" build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux

windows:
  stage: export
  script:
    - godot --editor --quit
    - mkdir -v -p build/windows
    - godot -v --export "Windows Desktop" build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows

# GitLab Pages Deploy
pages:
  stage: deploy
  dependencies:
    - web
  script:
    - rm -rf 
    - mv build/web/* public/
  artifacts:
    paths:
      - public
  only: 
    - main

cleanup:
  stage: cleanup
  when: always
  script:
    ls